// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVIZxs1xnkAxthDr3voXaEKoB5QfyC30',
    appId: '1:203938546384:android:63704fcdeae8ca02f514d5',
    messagingSenderId: '203938546384',
    projectId: 'appdoacoes-ccac2',
    storageBucket: 'appdoacoes-ccac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl1Nd6x2AwUcMQE2QO4wVBvtkTZERNNYo',
    appId: '1:203938546384:ios:ffcd76f851c972aef514d5',
    messagingSenderId: '203938546384',
    projectId: 'appdoacoes-ccac2',
    storageBucket: 'appdoacoes-ccac2.firebasestorage.app',
    iosBundleId: 'com.example.appmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl1Nd6x2AwUcMQE2QO4wVBvtkTZERNNYo',
    appId: '1:203938546384:ios:ffcd76f851c972aef514d5',
    messagingSenderId: '203938546384',
    projectId: 'appdoacoes-ccac2',
    storageBucket: 'appdoacoes-ccac2.firebasestorage.app',
    iosBundleId: 'com.example.appmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4JlMrdeG8v1wIc7zd_vSxmGQk3VS5U-U',
    appId: '1:203938546384:web:d4bf7e17cbbbcef2f514d5',
    messagingSenderId: '203938546384',
    projectId: 'appdoacoes-ccac2',
    authDomain: 'appdoacoes-ccac2.firebaseapp.com',
    storageBucket: 'appdoacoes-ccac2.firebasestorage.app',
    measurementId: 'G-R73Q0RDDH5',
  );

}